=== openxal/usp-xal/core/resources/xal/schemas/tablegroup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:element name="tablegroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="table" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="schema">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="attribute" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"/>												
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="java.lang.String"/>
															<xs:enumeration value="java.lang.Boolean"/>
															<xs:enumeration value="java.lang.Integer"/>
															<xs:enumeration value="java.lang.Double"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												
												<xs:attribute name="isPrimaryKey" type="xs:boolean" use="required"/>
												<xs:attribute name="defaultValue" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="table-attribute-name">
									<xs:selector xpath="attribute"/>
									<xs:field xpath="@name"/>
								</xs:unique>								
							</xs:element>
							<xs:element name="record" maxOccurs="unbounded">								
								<xs:complexType>
									<xs:anyAttribute processContents="lax"/>
								</xs:complexType>
							</xs:element>							
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	<xs:unique name="table-name">
		<xs:selector xpath="table"></xs:selector>
		<xs:field xpath="@name"></xs:field>
	</xs:unique>
	</xs:element>
</xs:schema>

=== openxal/usp-xal/core/test/resources/xal/schemas/tablegroup_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tablegroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tablegroup.xsd">
	<table name="tableA">
		<schema>
			<attribute name="id" type="java.lang.Integer" isPrimaryKey="true"/>
			<attribute name="name" type="java.lang.String" isPrimaryKey="false"/>
			<attribute name="active" type="java.lang.Boolean" isPrimaryKey="false" defaultValue="false"/>
			<attribute name="value" type="java.lang.Double" isPrimaryKey="false" defaultValue="0.0"/>
		</schema>
		<record id="1" name="Arthur"/>
		<record id="2" name="Bogomila" active="true"/>
		<record id="3" name="Cecile" defaultValue="1.0"/>
		<record id="4" name="Dent" active="true" defaultValue="3.14159"/>
	</table>
	<table name="tableB">
		<schema>
			<attribute name="id" type="java.lang.Integer" isPrimaryKey="true"/>
		</schema>
		<record id="1"/>
	</table>
</tablegroup>
